### PR TITLE
fix: Change expiry date parsing logic for boxes

### LINKED ISSUE #193: bug: export after commands
ran these commands  
```
assign n/Alice p/91234567
assign n/John Doe b/box-5:2027-01-01
export                       
```
and got failed to export.
Commands: `mark/remark/edit/addbox/editbox/deletebox` result in a new person being created without a driver. Export command checks !p.hasDriver() and throws an exception

### LINKED ISSUE #216: Expiry date should be fixed at the END OF MONTH
- owner should not be able to manually input any expiry date he likes as per our initial discussion
- for reference, this is how I implemented the ImportCommand to calculate expiry date based on number of mths the user subscribed

Image

### PR DESCRIPTION
**Pull request by lemonishi**
Fixes #193
Fixes #216 

## Changes
- Inputs no longer take in an explicit expiry date for boxes but instead parses it in the format `b/BOX_NAME:NUMBER_OF_MONTHS`. The expiry date will then be computed according to the number of months from the PRESENT date and gets set to the last day of the month. Refer to the user guide for more details
- Box commands now include preassigned drivers

## Tests
- Removed expiry date field from sample data
- For test cases to persist throughout time, we freeze the present time for tests to 8 April 2026 0000hrs, otherwise tests will fail when the month changes irl. This is the purpose of `DateTestUtil`

## Docs
- Updated the User Guide with the new format
- Removed all Person-level expiry date instances

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -95,13 +109,16 @@ public static Address parseAddress(String address) throws ParseException {
      *
      * @throws ParseException if the given {@code expiryDate} is invalid.
      */
-    public static ExpiryDate parseExpiryDate(String expiryDate) throws ParseException {
-        requireNonNull(expiryDate);
-        String trimmedExpiryDate = expiryDate.trim();
-        if (!ExpiryDate.isValidExpiryDate(trimmedExpiryDate)) {
-            throw new ParseException(ExpiryDate.MESSAGE_CONSTRAINTS);
+    public static ExpiryDate parseExpiryDate(String numOfMonthsString) throws ParseException {
```
Comment (concentratedsulfuricacid) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Important bug: there is no check for 0 and negative numbers
