### PR TITLE
fix: remark bug fixes

### LINKED ISSUE #273: [PE-D][Tester D] Multiple r/ prefixes accepted in remark command while earlier remarks r/... get ignored silently
Details:
The remark command is supposed to take only one r/REMARK parameter based on the User Guide. However, the app currently allows users to enter multiple r/ prefixes in the same command. When this happens, only the last remark is saved, and the earlier ones are ignored without any notice.

Steps to Reproduce:
remark 2 r/allergic to nuts r/night delivery

Expected:
The command should either reject multiple r/ prefixes or show a warning to the user that only the final single one remark is accepted.

Actual:
Screenshot below showing it silently accepts the last remark in the command, i.e. r/night delivery to be accepted without warnings.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #287: [PE-D][Tester C] Updating a remark removes the subscriber's assigned driver
### Description
After drivers have been assigned, using `remark` on a subscriber removes that subscriber's driver assignment even though the command is only supposed to update the remark.

### Steps to reproduce
1. Launch the app with sample data.
2. Run:
   ```text
   assign n/David Lim p/91234567 n/Priya Nair p/98765432
   ```
3. Confirm that at least one subscriber is assigned to David:
   ```text
   filter d/David
   ```
4. Run `list`, then choose one of David's assigned subscribers.
5. Run:
   ```text
   remark 1 r/leave at doorstep
   ```
   using the correct index for one of David's assigned subscribers.
6. Try filtering by David again.

### Expected
The subscriber's remark should be updated while their assigned driver remains unchanged.

### Actual
The subscriber disappears from the driver's filtered list because the driver assignment is removed.

### Why this matters
A simple note update should not silently undo delivery planning.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #291: [PE-D][Tester C] he command summary shows an invalid syntax for remark
### Description
The main `remark` section correctly documents the command as `remark INDEX r/REMARK`, but the command summary at the bottom omits the required `r/` prefix and gives an invalid example.

### Steps to reproduce
1. Scroll to the command summary in the UG.
2. Follow the documented summary syntax:
   ```text
   remark 2 leave at door
   ```

### Expected
The command summary should match the actual syntax accepted by the app.

### Actual
The summary shows `remark INDEX REMARK` and the example `remark 2 leave at door`, but the app requires:
```text
remark 2 r/leave at door
```

### Why this matters
Users relying on the command summary for quick reference will copy an invalid command and get an error.

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### LINKED ISSUE #327: [PE-D][Tester B] Editbox, deletebox, addbox commands have unintuitive command pattern
The editbox, deletebox and addbox commands select users by their full names.

e.g. `editbox n/NAME`, `addbox n/NAME`, `deletebox n/NAME`

rather than `edit INDEX`, `mark INDEX`, etc. 

This is inconsistent with other methods' use of a subscriber's index to select them, e.g. delete and edit.

A user would have to switch between selecting subscribers by index, and selecting subscribers by name, which is likely to disrupt their workflow especially for typing-oriented command inputs where typing errors can occur.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #329: [PE-D][Tester B] Edit and remark features have unintuitive output
After either filter or find is run, using either the edit or remark commands results in the correct output but returns the person list window view to the view if "list" had been called after. 

For instance, suppose we run: `filter box-2`:

Image

Then, we run: `edit 3 p/82438807`

We get: 

Image

Which is basically a return to the list view.

This is unintuitive as we lose the results of the current query if we perform any operation on the results of the filtered/found list.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by concentratedsulfuricacid**
fix: #273 
fix: #287

fixed issue of multiple remarks and driver assignment being removed after editing remarks

doc fix: #291 
doc fix: #327
doc fix #329 

fixed syntax for remark command in summary of UG

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/RemarkCommandParser.java [hunk 1]
```diff
@@ -33,17 +33,14 @@ public RemarkCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, RemarkCommand.MESSAGE_USAGE), pe);
         }
 
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_REMARKS);
```
Comment (jaris2203) [inline src/main/java/seedu/address/logic/parser/RemarkCommandParser.java:36]: Good use of existing methods for check for duplicate prefixes, I almost thought of creating another way to validate for another Command.

File: src/main/java/seedu/address/logic/commands/RemarkCommand.java [hunk 2]
```diff
@@ -50,9 +50,13 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToEdit = lastShownList.get(targetIndex.getZeroBased());
-        Person remarkedPerson = new Person(personToEdit.getName(), personToEdit.getPhone(), personToEdit.getEmail(),
-                personToEdit.getAddress(), personToEdit.getBoxes(), remark, personToEdit.getDeliveryStatus(),
-                personToEdit.getTags());
+        Person remarkedPerson = personToEdit.hasDriver()
```
Comment (jaris2203) [inline src/main/java/seedu/address/logic/commands/RemarkCommand.java:53]: Clean formatting makes this super readable!

**Review by jaris2203 — APPROVED** [review]
LGTM 👍
